# Generated by Django 4.2.2 on 2023-07-01 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectChatRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_1', to=settings.AUTH_USER_MODEL)),
                ('member_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
