# Generated by Django 4.2.2 on 2023-07-01 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_directchatroommember'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchatroommember',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='directchatroommember',
            name='type',
            field=models.CharField(default='DM', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='directchatroommember',
            unique_together={('member_1', 'member_2')},
        ),
    ]
