# Generated by Django 4.2.2 on 2023-07-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_directchatroommember_name_directchatroommember_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectChatRoomMember',
        ),
    ]
